wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685090912.544959
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 19
      - 23
      4: 3.9.7
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
max_len:
  desc: null
  value: 13
buckets:
  desc: null
  value: 50
